name: GPU Tests

on:
  workflow_call:
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:

  test-gpu:
    environment:
      name: slow-test-env
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.10"#todo matrix?
    runs-on:
      labels: int-linux-x64-4core-gpu-t4-ubuntu24.04-1
    name: GPU Test
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v1 #todo newer?
        with:
          python-version: '${{ matrix.python_version }}'
          use-cache: 'false'

      #- name: Allow unprivileged user namespaces
      #  run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Run without_db_integration_tests
                #todo make a set of gpu only tests? or is this seperated enough?
        #todo "Device set to use cpu" in outout. where from? do tests run with gpu?
        run: poetry run -- nox -s without_db_integration_tests