name: Onprem Integration Tests

on:
  workflow_call:
    secrets:
      DOCKER_USER:
          required: true
      DOCKER_PASSWORD:
          required: true
jobs:

  run-onprem-integration-tests:
    environment:
      name: slow-test-env
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.10"
    runs-on: ubuntu-24.04
    name: run-onprem-integration-tests
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v1
        with:
          python-version: '${{ matrix.python_version }}'

      - name: Allow unprivileged user namespaces
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Start test Docker-DB
        run: poetry run -- nox -s start_database

      - name: Run test onprem_integration_tests
        run: poetry run -- nox -s onprem_integration_tests
        env: # Set the secret as an input
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWORD }}