name: Saas Integration Tests


on:
  workflow_call:
    secrets:
      DOCKER_USER:
          required: true
      DOCKER_PASSWORD:
          required: true
      INTEGRATION_TEAM_SAAS_STAGING_HOST:
          required: true
      INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID:
          required: true
      INTEGRATION_TEAM_SAAS_STAGING_PAT:
          required: true

jobs:

  prep-testbed:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v1

      - id: set-matrix
        run: |
          ALL_TESTS=`poetry run -- nox -s saas_integration_tests`
          echo "matrix=$ALL_TESTS" >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  test-all:
    needs: prep-testbed
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.10"
        test-path: ${{fromJson(needs.prep-testbed.outputs.matrix)}}
    runs-on: ubuntu-24.04
    name: ${{ matrix.test-path.name }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v1
        with:
          python-version: '${{ matrix.python_version }}'

      - name: Allow unprivileged user namespaces
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: export slc
        run: poetry run -- nox -s export_slc

      - name: Run test ${{ matrix.test-path.name }}
        run: poetry run -- python ${{ matrix.test-path.path }}
        env: # Set the secret as an input
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWORD }}
