name: Saas Integration Tests


on:
  workflow_call:
    secrets:
      DOCKER_USER:
          required: true
      DOCKER_PASSWORD:
          required: true
      INTEGRATION_TEAM_SAAS_STAGING_HOST:
          required: true
      INTEGRATION_TEAM_SAAS_STAGING_ACCOUNT_ID:
          required: true
      INTEGRATION_TEAM_SAAS_STAGING_PAT:
          required: true

jobs:

  run-saas-integration-tests:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.10"
    runs-on: ubuntu-24.04
    name: run-saas-integration-tests
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v1
        with:
          python-version: '${{ matrix.python_version }}'

      - name: Allow unprivileged user namespaces
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: export slc
        run: poetry run -- nox -s export_slc

      - name: Run test saas_integration_tests
        run: poetry run -- nox -s saas_integration_tests
        env: # Set the secret as an input
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWORD }}
